### ISSUE TITLE
Wrong Version Displayed in Dropdown when Page Not Found

### ISSUE THREAD

**Issue by trueberryless** [HiDeoo/starlight-versions#11]
### Describe the bug

 On pages which don't exist in some past version, there exists a little bug when trying to go to the older version. A 404 page loads (as expected) but when I go back one step with Browser history, it loads the version displayed before, but shows the older version in the dropdown.

Not that this bug bugs me too much, but I wanted to mention it nonetheless. As I know you, you probably thought about how to handle such cases very well ❤️‍🩹 

This bug can only happen when `redirect` is set to `same-page`.

### To Reproduce

1. Go to https://starlight-versions-example.vercel.app/guides/guide-4/
2. Select either v1.0 or v2.0 in the dropdown.
3. You get redirected to the 404 page (expected behaviour).
4. You go back one step.
5. You land on the same page you visited in Step 1.
6. The dropdown says: `v1.0` (or `v2.0`) but NOT `latest` as expected.

### Expected behavior

The dropdown should always display the version which is currently active / shown on the page.

### How often does this bug happen?

Every time

### System Info

- Andriod
- happening in Arc and Chrome Browser

**Comment by HiDeoo** [comment]
Thanks for the report :raised_hands:

I've opened a fix for the same issue with the language selector in Starlight. Once the fix is discussed and validated there, I'll port the fix to this plugin as well.
