### ISSUE TITLE
demo of branching style versioning

### ISSUE THREAD

**Issue by DefinitelyMaybe** [HiDeoo/starlight-versions#3]
### Is your feature request related to a problem?

Hi there! coming from [threlte docs](https://threlte.xyz/) here. Thank you for your work on this starlight plugin as well as the others you've made, great stuff 👍 

I'm wanting to make a starlight version of our docs using this plugin. For right now, we can make do with folder based versioning but would love to see a branch based demo sometime in the future

### Describe the solution you'd like

a branch based versioning demo 🎉 

### Describe alternatives you've considered

Will do a folder based versioning for the moment

**Comment by HiDeoo** [comment]
Thanks for the interest and kind words :raised_hands:

As [mentioned](https://starlight-versions.vercel.app/guides/about-versioning/#versioning-strategies) in the documentation, this plugin was designed to be opionated towards a folder-based versioning strategy and I don't think I have any plans to support other strategies in this plugin.

My more long term idea was:

- Experiment and play more with this plugin as it addresses a specific need I have.
- Provide a potential reference for others who may want to experiment with other versioning plugins using different strategies.
- After working more on this plugin, consider if I want and have the time to provide additional plugins for other strategies.

Considering how different a folder-based strategy is from a branch (or tag) based one and how early this plugin is in its development, so far I don't think having a plugin supporting multiple strategies would be a good idea even maintenance-wise. Maybe work on this plugin will change my mind though.

**Comment by DefinitelyMaybe** [comment]
Ah, sorry I miss read the docs 😅

Haha opinions can change but happy to cross that bridge when we get there 👍
